"""initial schema

Revision ID: f0dd4683db21
Revises: 
Create Date: 2026-07-27 03:20:41.298619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0dd4683db21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('received_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('model_pricing',
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_per_mtok', sa.Float(), nullable=False),
    sa.Column('output_per_mtok', sa.Float(), nullable=False),
    sa.Column('cache_write_per_mtok', sa.Float(), nullable=False),
    sa.Column('cache_read_per_mtok', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('model')
    )
    op.create_table('usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('account_email', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=True),
    sa.Column('cwd', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('ended_at', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read', sa.Integer(), nullable=True),
    sa.Column('cache_write', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('cost_source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_day'), 'usage', ['day'], unique=False)
    op.create_index(op.f('ix_usage_email'), 'usage', ['email'], unique=False)
    op.create_index(op.f('ix_usage_session_id'), 'usage', ['session_id'], unique=False)
    op.create_index(op.f('ix_usage_timestamp'), 'usage', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('last_used_at', sa.String(), nullable=True),
    sa.Column('revoked_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_timestamp'), table_name='usage')
    op.drop_index(op.f('ix_usage_session_id'), table_name='usage')
    op.drop_index(op.f('ix_usage_email'), table_name='usage')
    op.drop_index(op.f('ix_usage_day'), table_name='usage')
    op.drop_table('usage')
    op.drop_table('model_pricing')
    op.drop_table('events')
    # ### end Alembic commands ###
